### ISSUE TITLE
Allow remapping of keys

### ISSUE THREAD

**Issue by deiga** [patrik-piskay/hyperterm-tabs#16]
The default keys might not fit everyone and thus it would be great if there was the possibility to change them.

**Comment by patrik-piskay** [comment]
Hi @deiga, sorry it's been a while since you created this, but I've just added support for this for Hyper 2 (currently in canary version, but it should go stable soon). [Here](https://github.com/patrik-piskay/hyperterm-tabs/blob/hyper-2-update/readme.md#usage) is the readme with the config option to remap keys, I'll release this once Hyper 2 stable is released.

In the meantime, if you are using the canary version of Hyper, you can start using this by replacing `index.js` file in `.hyper_plugins/node_modules/hyperterm-tabs` with Hyper 2 compatible [index.js](https://raw.githubusercontent.com/patrik-piskay/hyperterm-tabs/hyper-2-update/index.js)

**Comment by patrik-piskay** [comment]
Instead of replacing `node_modules` files, you can follow [this change](https://github.com/patrik-piskay/hyperterm-tabs/issues/19#issuecomment-370201111) if you are currently using Hyper canary (it will break with Hyper 1 stable, so be sure to only enable it on canary channel)

**Comment by patrik-piskay** [comment]
Closing, supported for Hyper v2 https://github.com/patrik-piskay/hyperterm-tabs#usage
